project:
  type: website

website:
  title: "Alex K Gold"
  twitter-card:
    creator: "@alexkgold"
  opengraph: true
  google-analytics: "UA-133127514-1"
  repo-url: https://github.com/akgold/akg_site
  repo-actions: [edit, issue]
  navbar:
    background: primary
    left:
      - text: "Talks"
        href: speaking.qmd
      - text: "Managing the First Year"
        href: mfy.qmd
      - text: "ðŸ“•DevOps For Data Science"
        href: https://akgold.github.io/do4ds/
    right:
      - href: about.qmd
        text: About
      - icon: fab fa-twitter
        href: https://twitter.com/alexkgold
      - icon: fab fa-github
        href: https://github.com/akgold/
      - icon: fab fa-linkedin-in
        href: https://www.linkedin.com/in/alexkgold/

format:
  html:
    theme:
      - flatly
      - styles.scss
    toc: true

editor: visual

